apiVersion: v1
kind: PersistentVolume
metadata:
  name: patch-pv
  labels:
    type: local
    app: awx-operator

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem #defautlvolume mode
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lab-patch-local

  nfs:
    path: /srv/nfs/k_test
    server: 127.0.0.1

  
#### rajout de la conf liée au NFS ou local? c'est en fonction de mon projet.
#### Mode kubernetes single node (cluster and worker-node at the same place (inside of my host))
